Repository 1-fredrikstad/sangbok, pull requests merged in 2021-04, with the labels that each got.

#65 Åpne sang i Spotify
  cms/schemas/documents/song.js
  frontend/package-lock.json
  frontend/src/api/songs.ts
  frontend/src/components/molecules/HeaderDetails.tsx
  frontend/src/components/organisms/SongDetail.tsx
Labels: Sprint 5 - Tertiary Features, feature

#75 E2E-testing med Cypress
  .github/workflows/ci.yml
  frontend/.eslintrc.js
  frontend/cypress.json
  frontend/cypress/fixtures/.gitkeep
  frontend/cypress/integration/access_lyrics.spec.js
  frontend/cypress/integration/activate_darkmode.spec.js
  frontend/cypress/integration/search_for_song.spec.js
  frontend/cypress/plugins/index.js
  frontend/cypress/support/commands.js
  frontend/cypress/support/index.js
  frontend/package-lock.json
  frontend/package.json
Labels: Sprint 5 - Tertiary Features, feature

#80 Add cypress to CI
  .github/workflows/ci.yml
  frontend/.eslintrc.js
  frontend/.github/workflows/ci.yml
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: Sprint 5 - Tertiary Features, feature

#82 Replace Lerna with Yarn Workspaces
  .github/workflows/ci.yml
  cms/package-lock.json
  cms/package.json
  cms/schemas/schema.js
  frontend/.gitignore
  frontend/.prettierignore
  frontend/cypress/integration/access_lyrics.spec.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/search.tsx
  frontend/pages/settings.tsx
  frontend/src/components/atoms/SearchInput.tsx
  frontend/src/components/organisms/SongList.tsx
  lerna.json
  package-lock.json
  package.json
  yarn.lock
Labels: Sprint 5 - Tertiary Features, documentation, enhancement, feature

#83 Add styling to settings
  frontend/pages/settings.tsx
  frontend/src/components/atoms/ThemeToggler.tsx
Labels: enhancement

#87 Oppdater dokumentasjon
  README.md
  package.json
Labels: Sprint 5 - Tertiary Features, documentation

#89 Disable video
  .github/workflows/ci.yml
  frontend/cypress.json
Labels: enhancement

#94 Legg til badges og recommendations
  README.md
  cms/.vscode/extensions.json
  frontend/.vscode/extensions.json
Labels: Sprint 5 - Tertiary Features, documentation

#97 Redesign application
  cms/sanity.json
  frontend/cypress/integration/access_lyrics.spec.js
  frontend/cypress/integration/search_for_song.spec.js
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/pages/search.tsx
  frontend/pages/settings.tsx
  frontend/public/images/camping.svg
  frontend/public/images/camping_dark.svg
  frontend/src/api/songs.tsx
  frontend/src/components/atoms/SearchInput.tsx
  frontend/src/components/molecules/Header.tsx
  frontend/src/components/molecules/HeaderDetails.tsx
  frontend/src/components/molecules/NavBar.tsx
  frontend/src/components/organisms/SongDetail.tsx
  frontend/src/components/organisms/SongList.tsx
  frontend/src/components/particles/theme.ts
  frontend/src/components/templates/Layout.tsx
  frontend/src/definitions/chakra/theme/foundations/colors.js
  frontend/src/definitions/chakra/theme/foundations/fontSizes.js
  frontend/src/definitions/chakra/theme/index.ts
  frontend/src/definitions/chakra/theme/styles.ts
  frontend/src/services/groq/client.ts
  frontend/src/types.ts
Labels: Sprint 5 - Tertiary Features, enhancement

#95 Add basic arrow-buttons for navigation
  frontend/pages/song/[slug].tsx
  frontend/src/components/atoms/navigationArrows.tsx
  frontend/src/components/molecules/HeaderDetails.tsx
  frontend/src/components/organisms/SongDetail.tsx
Labels: Sprint 5 - Tertiary Features, feature

#100 Remove i18 and fix deployment
  frontend/next-i18next.config.js
  frontend/next.config.js
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/public/meta.json
  frontend/src/components/organisms/SongList.tsx
  frontend/tsconfig.json
  yarn.lock
Labels: bug, enhancement

#101 Update imports
  frontend/pages/song/[slug].tsx
  frontend/src/components/atoms/NavigationArrows.tsx
Labels: bug, enhancement

#102 Last minute fix for standalone
  frontend/pages/_app.tsx
Labels: bug

#106 Revert3
  frontend/pages/_app.tsx
  frontend/src/components/molecules/NavBar.tsx
Labels: bug

#107 Navigation bar problems
  cms/.prettierignore
  cms/schemas/documents/song.js
  frontend/.eslintrc.js
  frontend/.prettierrc
  frontend/.prettierrc.js
  frontend/next.config.js
  frontend/pages/_app.tsx
  frontend/pages/_document.tsx
  frontend/pages/index.tsx
  frontend/pages/settings.tsx
  frontend/pages/song/[slug].tsx
  frontend/src/api/songs.tsx
  frontend/src/components/atoms/NavigationArrows.tsx
  frontend/src/components/atoms/SearchInput.tsx
  frontend/src/components/atoms/ThemeToggler.tsx
  frontend/src/components/molecules/Header.tsx
  frontend/src/components/molecules/HeaderDetails.tsx
  frontend/src/components/molecules/NavBar.tsx
  frontend/src/components/molecules/SingleVerse.tsx
  frontend/src/components/molecules/VerseChorusNumbering.tsx
  frontend/src/components/molecules/VerseNumbering.tsx
  frontend/src/components/organisms/SongDetail.tsx
  frontend/src/components/organisms/SongList.tsx
  frontend/src/components/particles/theme.ts
  frontend/src/components/templates/Layout.tsx
  frontend/src/services/groq/client.ts
Labels: bug, enhancement

#111 Enhancement: Better arrows and placement
  .github/workflows/ci.yml
  cms/package.json
  frontend/package.json
  frontend/src/components/atoms/NavigationArrows.tsx
  frontend/src/components/molecules/HeaderDetails.tsx
  frontend/src/components/organisms/SongDetail.tsx
  frontend/src/components/templates/Layout.tsx
  package.json
Labels: enhancement

#114 Add tut for installation
  README.md
Labels: documentation

#115 update slugify
  cms/schemas/documents/song.js
Labels: enhancement

#112 Add a song not found page
  frontend/pages/404.tsx
  frontend/public/images/404error.svg
Labels: enhancement

#113 Add PWA features
  .github/workflows/ci.yml
  .gitignore
  cms/yarn.lock
  frontend/cache.js
  frontend/next.config.js
  frontend/package.json
  frontend/pages/_document.tsx
  frontend/pages/index.tsx
  frontend/public/favicon.ico
  frontend/public/icons/16x16.png
  frontend/public/icons/180x180.png
  frontend/public/icons/192x192.png
  frontend/public/icons/32x32.png
  frontend/public/icons/512x512.png
  frontend/public/manifest.json
  frontend/yarn.lock
  package.json
Labels: Sprint 5 - Tertiary Features, feature

#118 Add logo to header and settings
  frontend/pages/index.tsx
  frontend/pages/settings.tsx
  frontend/public/images/logo-white.gif
  frontend/public/images/logo.gif
Labels: Sprint 6 - Finalize & Cleanup, enhancement

#123 Legg til eksempel på Spotify URI i Sanity
  cms/schemas/documents/song.js
Labels: enhancement

#125 Oppdatering av dokumentasjon og opprydding i kode
  README.md
  cms/README.md
  cms/package.json
  cms/plugins/.gitkeep
  cms/schemas/schema.js
  cms/yarn.lock
  frontend/.eslintignore
  frontend/.gitignore
  frontend/.prettierignore
  frontend/README.md
  frontend/next.config.js
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/pages/settings.tsx
  frontend/pages/song/[slug].tsx
  frontend/src/components/atoms/NavigationArrows.tsx
  frontend/src/components/atoms/SearchInput.tsx
  frontend/src/components/atoms/ThemeToggler.tsx
  frontend/src/components/molecules/HeaderDetails.tsx
  frontend/src/components/molecules/NavBar.tsx
  frontend/src/components/molecules/SingleVerse.tsx
  frontend/src/components/molecules/VerseChorusNumbering.tsx
  frontend/src/components/molecules/VerseNumbering.tsx
  frontend/src/components/organisms/SongDetail.tsx
  frontend/src/components/organisms/SongList.tsx
  frontend/src/components/templates/.gitkeep
  frontend/src/components/templates/Layout.tsx
  frontend/tsconfig.json
Labels: documentation, enhancement

#133 Oppdaterte bilder og slettet .gitkeep i mappe med innhold.
  assets/wiki/ny_organisasjon/client.png
  assets/wiki/ny_organisasjon/sanity-json.png
  cms/static/.gitkeep
Labels: documentation, enhancement
