Repository 1-fredrikstad/sangbok, pull requests merged in 2021-05, with the labels that each got.

#137 Update scripts and readme
  .github/workflows/ci.yml
  README.md
  frontend/README.md
  frontend/package.json
Labels: documentation, enhancement

#139 Add optional image field and add required to some sanity fields
  cms/schemas/documents/song.js
  cms/schemas/objects/songImage.js
  cms/schemas/schema.js
  frontend/src/api/songs.tsx
  frontend/src/components/organisms/SongDetail.tsx
  frontend/src/types.ts
Labels: Sprint 7 - Final Delivery

#138 Add padding and center navigation arrows
  frontend/cypress/integration/access_next_song.spec.js
  frontend/cypress/integration/access_song_from_song.spec.js
  frontend/src/components/atoms/NavigationArrows.tsx
  frontend/src/components/organisms/SongDetail.tsx
Labels: Sprint 7 - Final Delivery

#140 Increase clickable button area
  frontend/src/components/atoms/NavigationArrows.tsx
  frontend/src/components/organisms/SongDetail.tsx
Labels: enhancement
