Repository 1-fredrikstad/sangbok, pull requests merged in 2021-03, with the labels that each got.

#38 Toggle for darkmode
  frontend/src/App.tsx
  frontend/src/components/atoms/.gitkeep
  frontend/src/components/atoms/ThemeToggler.tsx
  frontend/src/components/pages/SettingsView.tsx
  frontend/tsconfig.json
Labels: Sprint 2 - Fundamentals, feature

#39 Add CI, Prettier and Eslint to the project + fix related linting issues
  .github/workflows/ci.yml
  .vscode/settings.json
  cms/package-lock.json
  cms/package.json
  frontend/.eslintrc.js
  frontend/.prettierrc.js
  frontend/dist/index.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/apolloClient.ts
  frontend/src/components/atoms/ThemeToggler.tsx
  frontend/src/components/molecules/NavBar.tsx
  frontend/src/components/pages/SearchView.tsx
  frontend/src/components/pages/SettingsView.tsx
  frontend/src/components/pages/SongView.tsx
  frontend/src/components/templates/SongTemplate.tsx
  frontend/src/i18n.ts
  frontend/src/index.tsx
  frontend/src/service-worker.ts
  frontend/src/serviceWorkerRegistration.ts
  frontend/tsconfig.json
Labels: Sprint 2 - Fundamentals, feature

#47 Update dependencies and refcator navbar and run prettier
  cms/schemas/documents/song.js
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/.prettierrc.js
  frontend/__generated__/GetLaunches.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_document.tsx
  frontend/pages/index.tsx
  frontend/pages/search.tsx
  frontend/pages/settings.tsx
  frontend/pages/song.tsx
  frontend/src/api/songs.ts
  frontend/src/components/atoms/SearchInput.tsx
  frontend/src/components/molecules/Header.tsx
  frontend/src/components/molecules/NavBar.tsx
  frontend/src/components/organisms/SongList.tsx
  frontend/src/components/pages/SearchView.tsx
  frontend/src/components/pages/SettingsView.tsx
  frontend/src/components/pages/SongView.tsx
  frontend/src/components/particles/theme.ts
  frontend/src/components/templates/Layout.tsx
  frontend/src/components/templates/SongTemplate.tsx
  package-lock.json
  package.json
Labels: Sprint 3 - Primary Features, feature

#48 Fix eslint
  frontend/pages/search.tsx
  frontend/pages/settings.tsx
  frontend/pages/song.tsx
  frontend/src/components/atoms/SearchInput.tsx
  frontend/src/components/atoms/ThemeToggler.tsx
  frontend/src/components/molecules/NavBar.tsx
  frontend/src/components/organisms/SongList.tsx
  frontend/src/definitions/chakra/theme/foundations/colors.js
  frontend/src/definitions/chakra/theme/foundations/fontSizes.js
  frontend/src/services/graphql/index.ts
Labels: Sprint 3 - Primary Features

#50 4 to 2 spaces
  frontend/.eslintrc.js
  frontend/.prettierrc
  frontend/.prettierrc.js
  frontend/apollo.config.js
  frontend/next-i18next.config.js
  frontend/next.config.js
  frontend/package-lock.json
  frontend/pages/_app.tsx
  frontend/pages/_document.tsx
  frontend/pages/index.tsx
  frontend/pages/search.tsx
  frontend/pages/settings.tsx
  frontend/pages/song/[id].tsx
  frontend/pages/song/index.tsx
  frontend/src/api/songs.ts
  frontend/src/components/atoms/SearchInput.tsx
  frontend/src/components/atoms/ThemeToggler.tsx
  frontend/src/components/molecules/Header.tsx
  frontend/src/components/molecules/NavBar.tsx
  frontend/src/components/organisms/SongList.tsx
  frontend/src/components/particles/theme.ts
  frontend/src/components/templates/Layout.tsx
  frontend/src/definitions/chakra/theme/foundations/colors.js
  frontend/src/definitions/chakra/theme/foundations/fontSizes.js
  frontend/src/definitions/chakra/theme/index.ts
  frontend/src/definitions/chakra/theme/styles.ts
  frontend/src/services/graphql/index.ts
  package-lock.json
Labels: Sprint 3 - Primary Features

#54 Fluent navigation
  README.md
  cms/package.json
  cms/schemas/documents/song.js
  frontend/.eslintrc.js
  frontend/LICENSE
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/pages/search.tsx
  frontend/pages/settings.tsx
  frontend/pages/song/[id].tsx
  frontend/pages/song/[slug].tsx
  frontend/src/api/songs.ts
  frontend/src/components/molecules/Header.tsx
  frontend/src/components/molecules/NavBar.tsx
  frontend/src/components/organisms/.gitkeep
  frontend/src/components/organisms/SongDetail.tsx
  frontend/src/components/organisms/SongList.tsx
  frontend/src/components/templates/Layout.tsx
  frontend/src/services/context/SlugProvider.tsx
  package-lock.json
Labels: Sprint 3 - Primary Features, feature, high pri, job story

#56 Metadata
  cms/package-lock.json
  frontend/pages/search.tsx
  frontend/src/components/molecules/Header.tsx
  frontend/src/components/molecules/HeaderDetails.tsx
  frontend/src/components/molecules/SongDetails.tsx
  frontend/src/components/organisms/SongDetail.tsx
  frontend/src/components/templates/Layout.tsx
  package-lock.json
Labels: Sprint 3 - Primary Features, feature, job story

#57 Song Melody
  frontend/src/components/molecules/HeaderDetails.tsx
  frontend/src/components/organisms/SongDetail.tsx
Labels: Sprint 3 - Primary Features, feature, job story
